### PR TITLE
fix:  remove unnecessary operator filtering and redundant storage fund display

### LINKED ISSUE #91: Operator filtering and sorting is currently unnecessary
There is currently no need to filter or sort the operators, as there are only two operators. We can bring back this feature once we open up to more operators. We should remove the filter and sorting functionality.

Image

### LINKED ISSUE #92: Active Positions does not need storage fund info
Storage fund info is included in the hover over the position value, it is not needed below the operator name. It should be removed.

Image

### PR DESCRIPTION
**Pull request by jfrank-summit**
## Summary

This PR implements the changes requested in issues #91 and #92 to simplify the UI for the current 2-operator scenario.

### Issue #91: Remove unnecessary operator filtering and sorting
**Problem**: With only 2 operators available, the filtering and sorting functionality adds unnecessary complexity to the UI.

**Changes**:
- Remove domain filter dropdown (Auto EVM selection)
- Remove sorting options (Total Staked, Tax sorting)
- Remove reset filters button and related functionality
- Keep only search functionality for operator name lookup
- Simplify results summary to remove domain-specific text

### Issue #92: Remove redundant storage fund info from active positions
**Problem**: Storage fund information is displayed redundantly in the position details when it's already available in the hover tooltip.

**Changes**:
- Remove storage fund display from position details section
- Storage fund info remains available in the hover tooltip
- Simplify position details to show only last updated timestamp
- Change grid layout from 2 columns to 1 column for cleaner display

### Files Changed
- `apps/web/src/components/operators/OperatorFilters.tsx` - Remove filtering/sorting UI
- `apps/web/src/components/positions/ActivePositionsTable.tsx` - Remove redundant storage fund display

### Testing
- All TypeScript types pass validation
- Linter passes with no errors
- Code follows project style guidelines
- UI is simplified and cleaner for the current 2-operator scenario

### Commits
- `fix: remove unnecessary operator filtering and sorting (issue #91)`
- `fix: remove redundant storage fund info from active positions (issue #92)`
- `refactor: remove unnecessary comment from OperatorFilters`
- `fix: apply prettier formatting to OperatorFilters`

Closes #91
Closes #92

### CODE REVIEW

File: apps/web/src/components/operators/OperatorFilters.tsx [hunk 1]
```diff
@@ -21,70 +20,12 @@ export const OperatorFilters: React.FC<OperatorFiltersProps> = ({
...
-            <option value="tax-desc">Sort: Tax (High to Low)</option>
-          </select>
-
-          {/* Reset Button */}
-          {hasActiveFilters() && (
-            <Button variant="outline" onClick={resetFilters} disabled={loading} className="text-sm">
-              Reset
-            </Button>
-          )}
+          {/* Search placeholder - filters removed since there are only 2 operators */}
```
Comment (jfrank-summit) [inline apps/web/src/components/operators/OperatorFilters.tsx:28]: @cursoragent this is an unnecessary comment.
